---
image: arpanrec/vaultmonorepo:7
stages:
  - test
  - vault-action
sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

terraform_apply:
  stage: vault-action
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - terraform/**/*
        - codified_vault/**/*
        - files/**/*
        - plugins/**/*
        - tasks/**/*
        - templates/**/*
        - vars/**/*
        - .gitlab-ci.yml
        - ansible.cfg
        - Dockerfile
        - inventory.yml
        - requirements.txt
        - site.yml
  before_script:
    - bw login --apikey --quiet
    - export BW_SESSION=$(bw unlock "${BW_MASTERPASSWORD}" --raw)
    - chmod 750 -R "${PWD}"
  script:
    - ansible-playbook ansible/site.yml
  after_script:
    - bw logout
    - bw status
