---
image: arpanrecme/vaultmonorepo:11
stages:
  - master_flow

master_flow:
  stage: master_flow
  before_script:
    - bw login --apikey --quiet
    - export BW_SESSION=$(bw unlock "${BW_MASTERPASSWORD}" --raw)
    - chmod 750 -R "${PWD}"
  script:
    - ansible-galaxy install -r requirements.yml
    - ansible-playbook site.yml --tags patch_server
    - ansible-playbook site.yml --tags install_vault
    - ansible-playbook site.yml --tags init_unseal
    - ansible-playbook site.yml --tags codified_vault
    - ansible-playbook site.yml --tags downstream
  after_script:
    - bw logout
    - bw status
