---
image: arpanrec/vaultmonorepo:3
stages:
  - test
  - vault-action
sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

terraform_apply:
  stage: vault-action
  rules:
    - changes:
        - terraform/**/*
        - ansible/**/*
        - files/**/*
        - .gitlab-ci.yml
        - inventory.yml
        - requirements.txt
        - ansible.cfg
        - Dockerfile
  before_script:
    - pwd
    - ls -al
    - bw login --apikey --quiet
    - chmod 750 -R "${PWD}"
    - ls -al
  script:
    - ansible-playbook ansible/site.yml --extra-vars "vault_mono_debug_no_log=0"
  after_script:
    - bw logout
    - bw status
