---
image: arpanrecme/vaultmonorepo:9
stages:
  - master_flow

master_flow:
  stage: master_flow
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - terraform/**/*
        - codified_vault/**/*
        - files/**/*
        - plugins/**/*
        - tasks/**/*
        - templates/**/*
        - vars/**/*
        - .gitlab-ci.yml
        - ansible.cfg
        - Dockerfile
        - inventory.yml
        - requirements.txt
        - site.yml
  before_script:
    - bw login --apikey --quiet
    - export BW_SESSION=$(bw unlock "${BW_MASTERPASSWORD}" --raw)
    - chmod 750 -R "${PWD}"
  script:
    - ansible-galaxy install -r requirements.yml
    - ansible-playbook site.yml
  after_script:
    - bw logout
    - bw status
