---
- name: Setup Vault Server
  hosts: vault_mono_server_ansible_inventory
  gather_facts: true
  become: true
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
    - name: Vault Monorepo | Setup Vault Server | Fail
      ansible.builtin.fail:
        msg: Required Debian Bullseye Systemd
      when: >
        ansible_facts['distribution_release'] | lower != 'bullseye'
        or
        ansible_facts['service_mgr'] | lower != 'systemd'
      tags:
        - always

    - name: Vault Monorepo | Setup Vault Server | Patch System
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/patch_system.yml"
      tags:
        - patch_server

    - name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/install_vault.yml"
      tags:
        - install_vault

    - name: Vault Monorepo | Setup Vault Server | Server TLS Certificate
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/vault_tls.yml"
      tags:
        - install_vault

  handlers:
    - name: Vault Monorepo | Setup Vault Server | Handlers | Restart Vault
      ansible.builtin.service:
        name: "{{ vault_mono_install_systemd_service_name }}"
        state: "{{ item }}"
      with_items:
        - reloaded
        - restarted
