---
- name: Get Server Information
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    vault_mono_server_ansible_inventory_name: vault_mono_server_ansible_inventory
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
    - name: Vault Monorepo | Get Server Information | Check for tools
      run_once: true
      ansible.builtin.shell: "command -v {{ item }} >/dev/null 2>&1"
      changed_when: false
      with_items:
        - terraform
        - bw
        - jq
        - gpg
        - ssh-keygen
      tags:
        - always

    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/get_prerequisite.yml"
      tags:
        - always

    - name: Vault Monorepo | Get Server Information | Create Server
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/create_server.yml"
      tags:
        - patch_server
        - install_vault
        - annihilation
