---
- name: Annihilate | Vault Install
  hosts: vault
  gather_facts: false
  become: false
  tasks:
    - name: Vault Monorepo | Annihilation | Gather Fact
      ansible.builtin.setup:
      tags:
        - annihilation
        - never

    - name: Vault Monorepo | Annihilation | Vault Install
      become: true
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/annihilate_vault_install.yml"
      tags:
        - annihilation
        - never

- name: Annihilation
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Vault Monorepo | Annihilation
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/annihilate_others.yml"
      tags:
        - annihilation
        - never
