collections:
  - name: community.general
    type: git
    source: https://github.com/ansible-collections/community.general
    version: 6.1.0
  - name: community.crypto
    type: git
    source: https://github.com/ansible-collections/community.crypto.git
    version: 2.9.0
roles:
  - name: geerlingguy.docker
    scm: git
    src: https://github.com/geerlingguy/ansible-role-docker.git
    version: 6.0.4
