collections:
  - name: community.general
    type: git
    source: https://github.com/ansible-collections/community.general
  - name: community.crypto
    type: git
    source: https://github.com/ansible-collections/community.crypto.git
roles:
  - name: geerlingguy.docker
    scm: git
    src: https://github.com/geerlingguy/ansible-role-docker.git
