---
- name: Get Server Information
  ansible.builtin.import_playbook: get_server.yml

- name: Get Server Information
  ansible.builtin.import_playbook: setup_vault.yml

- name: Get Server Information
  ansible.builtin.import_playbook: configure_vault.yml
