---
- name: Get Server Information
  ansible.builtin.import_playbook: playbook_create_server.yml

- name: Get Server Information
  ansible.builtin.import_playbook: playbook_setup_vault.yml

- name: Get Server Information
  ansible.builtin.import_playbook: playbook_configure_vault.yml
