---
- name: Vault Monorepo | Setup Vault Server | Patch System | Install upgrade and install python3-pip
  ansible.builtin.raw: apt-get update && apt-get install -y python3-pip
  register: vault_mono_system_patch_tmp_install_pip_result
  changed_when: "'0 upgraded, 0 newly installed' not in vault_mono_system_patch_tmp_install_pip_result.stdout_lines | last"

- name: Vault Monorepo | Setup Vault Server | Patch System | Set timezone as UTC
  community.general.timezone:
    name: UTC
    hwclock: UTC

- name: Vault Monorepo | Setup Vault Server | Patch System | Install required packages
  ansible.builtin.apt:
    name:
      [
        libcap2-bin,
        zip,
        unzip,
        net-tools,
        build-essential,
        tar,
        wget,
        curl,
        ca-certificates,
        sudo,
        systemd,
        telnet,
        gnupg2,
        apt-transport-https,
        lsb-release,
        software-properties-common,
        locales,
        systemd-timesyncd,
        network-manager,
        gnupg2,
        gnupg,
        pigz,
        cron,
        acl,
        ufw,
        vim,
        python3-pip,
        git,
        fontconfig,
        gtk-update-icon-cache,
        libnss3,
        libatk1.0-0,
        libatk-bridge2.0-0,
        libgtk-3-0,
        bzip2,
        libgbm-dev,
        libglib2.0-dev,
        libdrm-dev,
        libasound2,
        jq,
        zsh,
      ]

- name: Vault Monorepo | Setup Vault Server | Patch System | Install headers linux-headers-{{ ansible_kernel }}
  ansible.builtin.apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present
    update_cache: true

- name: Vault Monorepo | Setup Vault Server | Patch System | Ensure a locale exists as en_US.UTF-8
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present
  environment:
    PATH: /usr/sbin:{{ ansible_env.PATH }}

- name: Vault Monorepo | Setup Vault Server | Patch System | Create certificate directory
  ansible.builtin.file:
    path: /usr/local/share/ca-certificates
    state: directory
    mode: "0750"

- name: Vault Monorepo | Setup Vault Server | Patch System | Copy Certificate
  ansible.builtin.copy:
    src: "{{ vault_mono_prerequisite_local_file_root_ca_certificate }}"
    dest: "/usr/local/share/ca-certificates/{{ vault_mono_prerequisite_local_file_root_ca_certificate | basename }}"
    remote_src: false
    mode: "0644"

- name: Vault Monorepo | Setup Vault Server | Patch System | Update CA Trust
  ansible.builtin.command: update-ca-certificates
  register: vault_mono_system_patch_tmp_add_root_ca_result
  changed_when: >
    "0 added, 0 removed" not in vault_mono_system_patch_tmp_add_root_ca_result.stdout

- name: Vault Monorepo | Setup Vault Server | Patch System | Create wheel and sudo groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items:
    - wheel
    - sudo

- name: Vault Monorepo | Setup Vault Server | Patch System | Create Sudoers directory
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Vault Monorepo | Setup Vault Server | Patch System | Allow group permissions
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ item.file_loc }}"
    content: "{{ item.rule }}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - file_loc: 1000-root
      rule: "root ALL=(ALL:ALL) ALL"
    - file_loc: 1100-sudo
      rule: "%sudo ALL=(ALL:ALL) ALL"
    - file_loc: 1200-wheel
      rule: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"

- name: Vault Monorepo | Setup Vault Server | Patch System | Vault login group {{ vault_mono_system_patch_login_group }}
  ansible.builtin.group:
    name: "{{ vault_mono_system_patch_login_group }}"
    state: present

- name: Vault Monorepo | Setup Vault Server | Patch System | Add login user {{ vault_mono_system_patch_login_user }}
  ansible.builtin.user:
    name: "{{ vault_mono_system_patch_login_user }}"
    group: "{{ vault_mono_system_patch_login_group }}"
    create_home: true
    append: true
    groups:
      - wheel
    home: "{{ vault_mono_system_patch_homedir_login_user }}"
    shell: /bin/zsh
  register: vault_mono_system_patch_tmp_login_user_create_result

- name: Vault Monorepo | Setup Vault Server | Patch System | Check zshrc file
  ansible.builtin.stat:
    path: "{{ vault_mono_system_patch_tmp_login_user_create_result.home }}/.zshrc"
  register: vault_mono_system_patch_tmp_login_user_zshrc_stat

- name: Vault Monorepo | Setup Vault Server | Patch System | Create zshrc file
  when: not vault_mono_system_patch_tmp_login_user_zshrc_stat.stat.exists
  ansible.builtin.file:
    group: "{{ vault_mono_system_patch_login_group }}"
    path: "{{ vault_mono_system_patch_tmp_login_user_create_result.home }}/.zshrc"
    owner: "{{ vault_mono_system_patch_login_user }}"
    mode: "0644"
    state: touch

- name: Vault Monorepo | Setup Vault Server | Patch System | Set authorized key for login user {{ vault_mono_system_patch_login_user }}
  ansible.posix.authorized_key:
    user: "{{ vault_mono_system_patch_login_user }}"
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ lookup('ansible.builtin.file', vault_mono_prerequisite_local_file_openssh_public_key) }}"

- name: Vault Monorepo | Setup Vault Server | Patch System | SSHD Hardening Disable Password Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"

- name: Vault Monorepo | Setup Vault Server | Patch System | Disable Wifi MAC randomization
  community.general.ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    mode: "0775"
  with_items:
    - section: "device"
      option: "wifi.scan-rand-mac-address"
      value: "no"
    - section: "device-mac-randomization"
      option: "wifi.scan-rand-mac-address"
      value: "no"
    - section: "ifupdown"
      option: "managed"
      value: "true"
    - section: "main"
      option: "plugins"
      value: "ifupdown,keyfile"
    - section: "connection"
      option: "wifi.powersave"
      value: 2

- name: Vault Monorepo | Setup Vault Server | Patch System | Disable IPv6
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/70-disable-ipv6.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items:
    - name: net.ipv6.conf.all.disable_ipv6
      value: "1"
    - name: net.ipv6.conf.default.disable_ipv6
      value: "1"
    - name: net.ipv6.conf.lo.disable_ipv6
      value: "1"

- name: Vault Monorepo | Setup Vault Server | Patch System | Set a hostname
  ansible.builtin.hostname:
    name: "{{ vault_mono_system_patch_hostname }}"
    use: debian

- name: Vault Monorepo | Setup Vault Server | Patch System | Set Hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    owner: root
    group: root
    mode: "0644"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - regexp: '^127\.0\.0\.1'
      line: "127.0.0.1    localhost"
    - regexp: '^127\.0\.1\.1'
      line: "127.0.1.1    {{ vault_mono_system_patch_hostname }}"

- name: Vault Monorepo | Setup Vault Server | Patch System | Enable network services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: [NetworkManager, systemd-timesyncd, systemd-resolved, ufw, cron]

- name: Vault Monorepo | Setup Vault Server | Patch System | Create UFW postgresql application rules
  ansible.builtin.template:
    src: "{{ vault_mono_local_templates_dir }}/ufw-postgresql-db.j2"
    dest: /etc/ufw/applications.d/ufw-postgresql-db
    mode: "0644"

- name: Vault Monorepo | Setup Vault Server | Patch System | Disable ufw IPv6
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: "^IPV6="
    line: "IPV6=no"
    state: present

- name: Vault Monorepo | Setup Vault Server | Patch System | UFW Application Ports
  community.general.ufw:
    rule: allow
    name: "{{ item }}"
    state: enabled
  with_items:
    - OpenSSH
    - postgresql-db

- name: Vault Monorepo | Setup Vault Server | Patch System | Allow Other Ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - 8088
