---
- name: Vault Monorepo | Configure Vault | Initialize and Unseal | Get Vault Health Status
  environment: # https://stackoverflow.com/questions/47890394/ansible-uri-module-with-cacert-option
    SSL_CERT_FILE: "{{ vault_mono_local_file_root_ca_certificate }}"
  ansible.builtin.uri:
    url: "{{ vault_mono_global_config.VAULT.PROTOCOL }}://{{ vault_mono_global_config.VAULT.FQDN }}:{{ vault_mono_global_config.VAULT.PORT }}/v1/sys/health"
    method: GET
    # ca_path: "{{ vault_mono_local_file_root_ca_certificate }}"
    client_cert: "{{ vault_mono_local_file_client_certificate }}"
    client_key: "{{ vault_mono_local_file_client_private_key }}"
    status_code: [429, 472, 473, 501, 503, 200]
    validate_certs: true
  register: vault_mono_init_unseal_tmp_health

- name: Vault Monorepo | Configure Vault | Initialize and Unseal | Initialize
  when: not vault_mono_init_unseal_tmp_health.json.initialized
  no_log: "{{ vault_mono_debug_no_log }}"
  environment: # https://stackoverflow.com/questions/47890394/ansible-uri-module-with-cacert-option
    SSL_CERT_FILE: "{{ vault_mono_local_file_root_ca_certificate }}"
  ansible.builtin.uri:
    url: "{{ vault_mono_global_config.VAULT.PROTOCOL }}://{{ vault_mono_global_config.VAULT.FQDN }}:{{ vault_mono_global_config.VAULT.PORT }}/v1/sys/init"
    method: POST
    # ca_path: "{{ vault_mono_local_file_root_ca_certificate }}"
    client_cert: "{{ vault_mono_local_file_client_certificate }}"
    client_key: "{{ vault_mono_local_file_client_private_key }}"
    validate_certs: true
    body_format: json
    status_code: 200
    body:
      secret_shares: 5
      secret_threshold: 3
  register: vault_mono_init_unseal_tmp_sys_init
  changed_when: true

- name: Vault Monorepo | Configure Vault | Initialize and Unseal | Reset init secret
  no_log: "{{ vault_mono_debug_no_log }}"
  when: vault_mono_init_unseal_tmp_sys_init.json is defined and vault_mono_init_unseal_tmp_sys_init.json.root_token is defined
  ansible.builtin.set_fact:
    vault_mono_init_unseal_fact_init_secrets: "{{ vault_mono_init_unseal_tmp_sys_init.json }}"

- name: Vault Monorepo | Configure Vault | Initialize and Unseal | Write init secrets To File
  when: vault_mono_init_unseal_tmp_sys_init.json is defined and vault_mono_init_unseal_tmp_sys_init.json.root_token is defined
  no_log: "{{ vault_mono_debug_no_log }}"
  ansible.builtin.copy:
    content: |
      {{ vault_mono_init_unseal_tmp_sys_init.json | to_nice_json(indent=2) }}
    dest: "{{ vault_mono_local_file_vault_init_secrets }}"
    mode: "0400"

- name: Vault Monorepo | Configure Vault | Initialize and Unseal | Unseal
  when: >
    (
      vault_mono_init_unseal_tmp_sys_init.json is defined and vault_mono_init_unseal_tmp_sys_init.json.root_token is defined
    )
    or
    (
      vault_mono_init_unseal_tmp_health.json.initialized and vault_mono_init_unseal_tmp_health.json.sealed
    )
  environment: # https://stackoverflow.com/questions/47890394/ansible-uri-module-with-cacert-option
    SSL_CERT_FILE: "{{ vault_mono_local_file_root_ca_certificate }}"
  no_log: "{{ vault_mono_debug_no_log }}"
  ansible.builtin.uri:
    url: "{{ vault_mono_global_config.VAULT.PROTOCOL }}://{{ vault_mono_global_config.VAULT.FQDN }}:{{ vault_mono_global_config.VAULT.PORT }}/v1/sys/unseal"
    method: POST
    # ca_path: "{{ vault_mono_local_file_root_ca_certificate }}"
    client_cert: "{{ vault_mono_local_file_client_certificate }}"
    client_key: "{{ vault_mono_local_file_client_private_key }}"
    validate_certs: true
    body_format: json
    status_code: 200
    body:
      key: "{{ item }}"
  changed_when: true
  with_items:
    - "{{ vault_mono_init_unseal_fact_init_secrets['keys'][0] }}"
    - "{{ vault_mono_init_unseal_fact_init_secrets['keys'][1] }}"
    - "{{ vault_mono_init_unseal_fact_init_secrets['keys'][2] }}"

- name: Vault Monorepo | Configure Vault | Initialize and Unseal | Fail if not active
  environment: # https://stackoverflow.com/questions/47890394/ansible-uri-module-with-cacert-option
    SSL_CERT_FILE: "{{ vault_mono_local_file_root_ca_certificate }}"
  ansible.builtin.uri:
    url: "{{ vault_mono_global_config.VAULT.PROTOCOL }}://{{ vault_mono_global_config.VAULT.FQDN }}:{{ vault_mono_global_config.VAULT.PORT }}/v1/sys/health"
    method: GET
    # ca_path: "{{ vault_mono_local_file_root_ca_certificate }}"
    client_cert: "{{ vault_mono_local_file_client_certificate }}"
    client_key: "{{ vault_mono_local_file_client_private_key }}"
    status_code: 200
    validate_certs: true

- name: Vault Monorepo | Configure Vault | Initialize and Unseal | Revoke Root Token
  environment: # https://stackoverflow.com/questions/47890394/ansible-uri-module-with-cacert-option
    SSL_CERT_FILE: "{{ vault_mono_local_file_root_ca_certificate }}"
  ansible.builtin.uri:
    url:
      "{{ vault_mono_global_config.VAULT.PROTOCOL }}://{{ vault_mono_global_config.VAULT.FQDN }}:\
      {{ vault_mono_global_config.VAULT.PORT }}/v1/auth/token/revoke-self"
    method: POST
    # ca_path: "{{ vault_mono_local_file_root_ca_certificate }}"
    client_cert: "{{ vault_mono_local_file_client_certificate }}"
    client_key: "{{ vault_mono_local_file_client_private_key }}"
    status_code: [204, 403]
    validate_certs: true
    return_content: true
    headers:
      "X-Vault-Token": "{{ vault_mono_init_unseal_fact_init_secrets.root_token }}"
  register: vault_mono_init_unseal_tmp_remove_root_token
  changed_when: vault_mono_init_unseal_tmp_remove_root_token.status == 204
