---
- name: Terraform Cloud Management | Organization | Reset new org stat
  ansible.builtin.set_fact:
    rl_tef_org_is_newly_created: false
    rl_tef_api_token: "{{ lookup('ansible.builtin.file', vault_mono_local_file_terraform_cloud_tf_prod_token) | string }}"

- name: Terraform Cloud Management | Organization | Get organizations
  no_log: "{{ vault_mono_debug_no_log }}"
  ansible.builtin.uri:
    url: "{{ rl_tef_api_endpoint }}/organizations/{{ vault_mono_codified_vault_tfe_org_name }}"
    headers:
      Authorization: "Bearer {{ rl_tef_api_token }}"
      content-type: "application/vnd.api+json"
    status_code: 200,404
  register: rl_tef_org_details

- name: Terraform Cloud Management | Organization | Create organizations
  when: rl_tef_org_details.status == 404
  block:
    - name: Terraform Cloud Management | Organization | Create organizations | Create new org
      no_log: "{{ vault_mono_debug_no_log }}"
      ansible.builtin.uri:
        method: POST
        url: "{{ rl_tef_api_endpoint }}/organizations"
        body_format: json
        body:
          data:
            type: "organizations"
            attributes:
              name: "{{ vault_mono_codified_vault_tfe_org_name }}"
              email: "{{ vault_mono_codified_vault_tfe_org_email }}"
              collaborator-auth-policy: "{{ vault_mono_codified_vault_tfe_org_collaborator_auth_policy | default(omit) }}"
        status_code: 201
        headers:
          Authorization: "Bearer {{ rl_tef_api_token }}"
          content-type: "application/vnd.api+json"
      register: rl_tef_organization_create_response
      changed_when: rl_tef_organization_create_response.status == 201
      failed_when: rl_tef_organization_create_response.status != 201
    - name: Terraform Cloud Management | Organization | Create organizations | Get new organization details
      no_log: "{{ vault_mono_debug_no_log }}"
      ansible.builtin.uri:
        url: "{{ rl_tef_api_endpoint }}/organizations/{{ vault_mono_codified_vault_tfe_org_name }}"
        headers:
          Authorization: "Bearer {{ rl_tef_api_token }}"
          content-type: "application/vnd.api+json"
        status_code: 200
      register: rl_tef_org_new_org_response
    - name: Terraform Cloud Management | Workspaces | Create workspace | Reset fact with new
      ansible.builtin.set_fact:
        rl_tef_org_details: "{{ rl_tef_org_new_org_response }}"
        rl_tef_org_is_newly_created: true
      when: rl_tef_organization_create_response.changed

- name: Terraform Cloud Management | Organization | Update organization
  when: not rl_tef_org_is_newly_created
  block:
    - name: Terraform Cloud Management | Organization | Update organization | Update email id
      no_log: "{{ vault_mono_debug_no_log }}"
      when: (vault_mono_codified_vault_tfe_org_email is defined) and rl_tef_org_details.json.data.attributes.email != vault_mono_codified_vault_tfe_org_email
      ansible.builtin.uri:
        method: PATCH
        url: "{{ rl_tef_api_endpoint }}/organizations/{{ vault_mono_codified_vault_tfe_org_name }}"
        body_format: json
        body:
          data:
            type: "organizations"
            attributes:
              email: "{{ vault_mono_codified_vault_tfe_org_email }}"
        status_code: 200
        headers:
          Authorization: "Bearer {{ rl_tef_api_token }}"
          content-type: "application/vnd.api+json"
      register: rl_tef_organization_update_email_response
      changed_when: rl_tef_organization_update_email_response.status == 200
      failed_when: rl_tef_organization_update_email_response.status != 200

    - name: Terraform Cloud Management | Organization | Update organization | Update Authentication Factor
      no_log: "{{ vault_mono_debug_no_log }}"
      when: (vault_mono_codified_vault_tfe_org_collaborator_auth_policy is defined) and rl_tef_org_details.json.data.attributes["collaborator-auth-policy"] != vault_mono_codified_vault_tfe_org_collaborator_auth_policy
      ansible.builtin.uri:
        method: PATCH
        url: "{{ rl_tef_api_endpoint }}/organizations/{{ vault_mono_codified_vault_tfe_org_name }}"
        body_format: json
        body:
          data:
            type: "organizations"
            attributes:
              collaborator-auth-policy: "{{ vault_mono_codified_vault_tfe_org_collaborator_auth_policy }}"
        status_code: 200
        headers:
          Authorization: "Bearer {{ rl_tef_api_token }}"
          content-type: "application/vnd.api+json"
      register: rl_tef_organization_update_mfa_response
      changed_when: rl_tef_organization_update_mfa_response.status == 200
      failed_when: rl_tef_organization_update_mfa_response.status != 200

## Workspace

- name: Terraform Cloud Management | Workspaces | Reset new Workspace stat | {{ vault_mono_codified_vault_tfe_org_workspace_name }}
  ansible.builtin.set_fact:
    rl_tef_workspace_is_newly_created: false

- name: Terraform Cloud Management | Workspaces | Get Workspaces | {{ vault_mono_codified_vault_tfe_org_workspace_name }}
  no_log: "{{ vault_mono_debug_no_log }}"
  ansible.builtin.uri:
    url: "{{ rl_tef_api_endpoint }}/organizations/{{ vault_mono_codified_vault_tfe_org_name }}/workspaces/{{ vault_mono_codified_vault_tfe_org_workspace_name }}"
    headers:
      Authorization: "Bearer {{ rl_tef_api_token }}"
      content-type: "application/vnd.api+json"
    status_code: 200,404
  register: rl_tef_workspace_response

- name: Terraform Cloud Management | Workspaces | Create workspace | {{ vault_mono_codified_vault_tfe_org_workspace_name }}
  when: rl_tef_workspace_response.status == 404
  block:
    - name: Terraform Cloud Management | Workspaces | Create workspace | Create new workspace | {{ vault_mono_codified_vault_tfe_org_workspace_name }}
      no_log: "{{ vault_mono_debug_no_log }}"
      ansible.builtin.uri:
        method: POST
        url: "{{ rl_tef_api_endpoint }}/organizations/{{ vault_mono_codified_vault_tfe_org_name }}/workspaces"
        body_format: json
        body:
          data:
            type: "workspaces"
            attributes:
              name: "{{ vault_mono_codified_vault_tfe_org_workspace_name }}"
              auto-apply: "{{ auto_apply | default(omit) | bool }}"
              execution-mode: "{{ vault_mono_codified_vault_tfe_org_workspace_execution_mode | default(omit) }}"
        status_code: 201
        headers:
          Authorization: "Bearer {{ rl_tef_api_token }}"
          content-type: "application/vnd.api+json"
      register: rl_tef_workspace_create_response
      changed_when: rl_tef_workspace_create_response.status == 201
      failed_when: rl_tef_workspace_create_response.status != 201

    - name: Terraform Cloud Management | Workspaces | Create workspace | Get new Workspace details | {{ vault_mono_codified_vault_tfe_org_workspace_name }}
      no_log: "{{ vault_mono_debug_no_log }}"
      ansible.builtin.uri:
        url: "{{ rl_tef_api_endpoint }}/organizations/{{ vault_mono_codified_vault_tfe_org_name }}/workspaces/{{ vault_mono_codified_vault_tfe_org_workspace_name }}"
        headers:
          Authorization: "Bearer {{ rl_tef_api_token }}"
          content-type: "application/vnd.api+json"
        status_code: 200
      register: rl_tef_workspace_details_create_response

    - name: Terraform Cloud Management | Workspaces | Create workspace | Reset fact with new | {{ vault_mono_codified_vault_tfe_org_workspace_name }}
      ansible.builtin.set_fact:
        rl_tef_workspace_response: "{{ rl_tef_workspace_details_create_response }}"
        rl_tef_workspace_is_newly_created: true
      when: rl_tef_workspace_create_response.changed

- name: Terraform Cloud Management | Workspaces | Update Workspace | {{ vault_mono_codified_vault_tfe_org_workspace_name }}
  when: not rl_tef_workspace_is_newly_created
  block:
    - name: Terraform Cloud Management | Workspaces | Update Workspace | auto-apply | {{ vault_mono_codified_vault_tfe_org_workspace_name }}
      no_log: "{{ vault_mono_debug_no_log }}"
      when: (rl_tef_workspace_response.json.data.attributes["auto-apply"] | bool) != (vault_mono_codified_vault_tfe_org_workspace_auto_apply | bool)
      ansible.builtin.uri:
        method: PATCH
        url: "{{ rl_tef_api_endpoint }}/organizations/{{ vault_mono_codified_vault_tfe_org_name }}/workspaces/{{ vault_mono_codified_vault_tfe_org_workspace_name }}"
        body_format: json
        body:
          data:
            type: "workspaces"
            attributes:
              auto-apply: "{{ vault_mono_codified_vault_tfe_org_workspace_auto_apply | default(omit) | bool }}"
        status_code: 200
        headers:
          Authorization: "Bearer {{ rl_tef_api_token }}"
          content-type: "application/vnd.api+json"
      register: rl_tef_workspace_update_auto_apply_response
      changed_when: rl_tef_workspace_update_auto_apply_response.status == 200

    - name: Terraform Cloud Management | Workspaces | Update Workspace | execution-mode | {{ vault_mono_codified_vault_tfe_org_workspace_name }}
      no_log: "{{ vault_mono_debug_no_log }}"
      when: >
        (vault_mono_codified_vault_tfe_org_workspace_execution_mode is defined)
        and
        (vault_mono_codified_vault_tfe_org_workspace_execution_mode | length > 1)
        and
        (
          (rl_tef_workspace_response.json.data.attributes["execution-mode"])
          !=
          (vault_mono_codified_vault_tfe_org_workspace_execution_mode)
        )
      ansible.builtin.uri:
        method: PATCH
        url: "{{ rl_tef_api_endpoint }}/organizations/{{ vault_mono_codified_vault_tfe_org_name }}/workspaces/{{ vault_mono_codified_vault_tfe_org_workspace_name }}"
        body_format: json
        body:
          data:
            type: "workspaces"
            attributes:
              execution-mode: "{{ vault_mono_codified_vault_tfe_org_workspace_execution_mode }}"
        status_code: 200
        headers:
          Authorization: "Bearer {{ rl_tef_api_token }}"
          content-type: "application/vnd.api+json"
      register: rl_tef_workspace_update_auto_apply_response
      changed_when: rl_tef_workspace_update_auto_apply_response.status == 200
