---
- name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Create mandatory directories
  ansible.builtin.file:
    state: directory
    path: "{{ vault_mono_prerequisite_files_dir }}"
    mode: "0750"

- name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden
  block:
    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | pipefail set
      ansible.builtin.set_fact:
        vault_mono_prerequisite_tmp_pipefail_set: "" #"set -eo pipefail"

    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | OPENSSH PRIVATE KEY
      no_log: "{{ vault_mono_debug_no_log }}"
      block:
        - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | OPENSSH PRIVATE KEY | SHA
          ansible.builtin.set_fact:
            vault_mono_prerequisite_tmp_openssh_private_key_id: F6x3hDIMdersLA/lwMaaJZMx3c0uowgw7Bv5xX2NFa0

        - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | OPENSSH PRIVATE KEY | Download Private key
          ansible.builtin.shell: |+
            {{ vault_mono_prerequisite_tmp_pipefail_set }}

            bw get attachment id_rsa \
            --itemid $(bw get item '{{ vault_mono_prerequisite_tmp_openssh_private_key_id }}' \
            --raw | jq .id -r) \
            --output "{{ vault_mono_prerequisite_local_file_openssh_private_key }}"

            chmod 400 "{{ vault_mono_prerequisite_local_file_openssh_private_key }}"
          args:
            creates: "{{ vault_mono_prerequisite_local_file_openssh_private_key }}"

        - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | OPENSSH PRIVATE KEY | Get private key passphrase
          ansible.builtin.shell: |+
            {{ vault_mono_prerequisite_tmp_pipefail_set }}

            bw get password '{{ vault_mono_prerequisite_tmp_openssh_private_key_id }}' > {{ vault_mono_prerequisite_local_file_openssh_passphrase_private_key }}
          args:
            creates: "{{ vault_mono_prerequisite_local_file_openssh_passphrase_private_key }}"

    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | Linode api token
      no_log: "{{ vault_mono_debug_no_log }}"
      ansible.builtin.shell: |+
        {{ vault_mono_prerequisite_tmp_pipefail_set }}

        bw get item 'Linode' --raw | \
        jq '.fields |
        .[] |
        select(.name == "LINODE_CLI_PROD_TOKEN") |
        .value' -r > {{ vault_mono_prerequisite_local_file_linode_cli_prod_token }}
      args:
        creates: "{{ vault_mono_prerequisite_local_file_linode_cli_prod_token }}"

    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | ROOT CA
      no_log: "{{ vault_mono_debug_no_log }}"
      block:
        - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | ROOT CA | SHA
          ansible.builtin.set_fact:
            vault_mono_prerequisite_tmp_rootca_rsa_private_key_sha256: b4:f2:e1:1b:61:4f:8f:23:f5:27:b7:da:9b:57:0b:8c:47:62:7d:97:6a:33:0c:a3:70:e0:43:f9:ac:fa:e7:83

        - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | ROOT CA | Download Private Key
          ansible.builtin.shell: |+
            {{ vault_mono_prerequisite_tmp_pipefail_set }}

            bw get attachment key.pem \
            --itemid $(bw get item '{{ vault_mono_prerequisite_tmp_rootca_rsa_private_key_sha256 }}' --raw | jq .id -r) \
            --output "{{ vault_mono_prerequisite_local_file_root_ca_private_key }}"
          args:
            creates: "{{ vault_mono_prerequisite_local_file_root_ca_private_key }}"

        - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | ROOT CA | Get private key passphrase
          ansible.builtin.shell: |+
            {{ vault_mono_prerequisite_tmp_pipefail_set }}

            bw get password \
             '{{ vault_mono_prerequisite_tmp_rootca_rsa_private_key_sha256 }}' > {{ vault_mono_prerequisite_local_file_root_ca_passphrase_private_key }}
          args:
            creates: "{{ vault_mono_prerequisite_local_file_root_ca_passphrase_private_key }}"

    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | Gitlab GL_PROD_API_KEY
      no_log: "{{ vault_mono_debug_no_log }}"
      ansible.builtin.shell: |+
        {{ vault_mono_prerequisite_tmp_pipefail_set }}

        bw get item 'Gitlab' --raw | \
        jq '.fields |
        .[] |
        select(.name == "GL_PROD_API_KEY") |
        .value' -r > {{ vault_mono_prerequisite_local_file_gitlab_gl_prod_api_key }}
      args:
        creates: "{{ vault_mono_prerequisite_local_file_gitlab_gl_prod_api_key }}"

    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | Github GH_PROD_API_TOKEN
      no_log: "{{ vault_mono_debug_no_log }}"
      ansible.builtin.shell: |+
        {{ vault_mono_prerequisite_tmp_pipefail_set }}

        bw get item 'Github' --raw | \
        jq '.fields |
        .[] |
        select(.name == "GH_PROD_API_TOKEN") |
        .value' -r > {{ vault_mono_prerequisite_local_file_github_gh_prod_api_token }}
      args:
        creates: "{{ vault_mono_prerequisite_local_file_github_gh_prod_api_token }}"

    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | Ansible Galaxy API Key
      no_log: "{{ vault_mono_debug_no_log }}"
      ansible.builtin.shell: |+
        {{ vault_mono_prerequisite_tmp_pipefail_set }}

        bw get item 'Ansible galaxy' --raw | \
        jq '.fields |
        .[] |
        select(.name == "GALAXY_API_KEY") |
        .value' -r > {{ vault_mono_prerequisite_local_file_ansible_galaxy_api_key }}
      args:
        creates: "{{ vault_mono_prerequisite_local_file_ansible_galaxy_api_key }}"

    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | HashiCorp Terraform Cloud API Token
      no_log: "{{ vault_mono_debug_no_log }}"
      ansible.builtin.shell: |+
        {{ vault_mono_prerequisite_tmp_pipefail_set }}

        bw get item 'HashiCorp Terraform cloud' --raw | \
        jq '.fields |
        .[] |
        select(.name == "TF_PROD_TOKEN") |
        .value' -r > {{ vault_mono_prerequisite_local_file_terraform_cloud_tf_prod_token }}
      args:
        creates: "{{ vault_mono_prerequisite_local_file_terraform_cloud_tf_prod_token }}"

    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | Remove empty lines from files
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '(\n\s*$)'
        replace: ""
        mode: "600"
      with_items:
        - "{{ vault_mono_prerequisite_local_file_linode_cli_prod_token }}"
        - "{{ vault_mono_prerequisite_local_file_gitlab_gl_prod_api_key }}"
        - "{{ vault_mono_prerequisite_local_file_github_gh_prod_api_token }}"
        - "{{ vault_mono_prerequisite_local_file_ansible_galaxy_api_key }}"
        - "{{ vault_mono_prerequisite_local_file_terraform_cloud_tf_prod_token }}"
  rescue:
    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | Something Whent Wrong | Remove directory
      ansible.builtin.file:
        path: "{{ vault_mono_prerequisite_files_dir }}"
        state: absent

    - name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Bitwarden | Something Whent Wrong | fail
      ansible.builtin.fail:
        msg: Check errors above with DEBUG=true

- name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Remove Password from OPENSSH PRIVATE KEY
  ansible.builtin.shell: |+
    cp {{ vault_mono_prerequisite_local_file_openssh_private_key }} {{ vault_mono_prerequisite_local_file_openssh_nopass_private_key }}
    chmod 600 {{ vault_mono_prerequisite_local_file_openssh_nopass_private_key }}
    ssh-keygen -p \
      -P {{ lookup('ansible.builtin.file', vault_mono_prerequisite_local_file_openssh_passphrase_private_key) }} \
      -N '' -f {{ vault_mono_prerequisite_local_file_openssh_nopass_private_key }}
  args:
    creates: "{{ vault_mono_prerequisite_local_file_openssh_nopass_private_key }}"

- name: Vault Monorepo | Get Server Information | Get Prerequisite Files | Remove Password from ROOT CA Private Key
  ansible.builtin.shell: |+
    openssl rsa -in {{ vault_mono_prerequisite_local_file_root_ca_private_key }} \
        -passin pass:{{ lookup('ansible.builtin.file', vault_mono_prerequisite_local_file_root_ca_passphrase_private_key) }} \
        -passout pass:"" \
        -out {{ vault_mono_prerequisite_local_file_root_ca_no_pass_private_key }}
  args:
    creates: "{{ vault_mono_prerequisite_local_file_root_ca_no_pass_private_key }}"
