---
- name: Vault Monorepo | Configure Vault | Get Vault Initial Secret | Check for existing file
  ansible.builtin.stat:
    path: "{{ vault_mono_local_file_vault_init_secrets }}"
  register: vault_mono_local_file_stat_vault_init_secrets

- name: Vault Monorepo | Configure Vault | Get Vault Initial Secret | GitLab
  when: not vault_mono_local_file_stat_vault_init_secrets.stat.exists
  block:
    - name: Vault Monorepo | Configure Vault | Get Vault Initial Secret | GitLab | Include variables
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/vars/gitlab_artifacts.yml"

    - name: Vault Monorepo | Configure Vault | Get Vault Initial Secret | GitLab | Check for existing
      no_log: "{{ vault_mono_debug_no_log }}"
      ansible.builtin.uri:
        url: "https://gitlab.com/api/v4/projects/\
          {{ vault_mono_gitlab_artifacts_project_id }}/variables/\
          {{ vault_mono_gitlab_artifacts_vault_cicd_variable_key_init_file }}"
        method: GET
        headers:
          "PRIVATE-TOKEN": "{{ lookup('ansible.builtin.file', vault_mono_prerequisite_local_file_gitlab_gl_prod_api_key) | trim }}"
        status_code:
          - 200
          - 404
      register: vault_mono_init_unseal_tmp_gitlab_variable_secret_response

    - name: Vault Monorepo | Configure Vault | Get Vault Initial Secret | GitLab | Write to file
      when: vault_mono_init_unseal_tmp_gitlab_variable_secret_response.status == 200
      no_log: "{{ vault_mono_debug_no_log }}"
      ansible.builtin.copy:
        content: |
          {{ vault_mono_init_unseal_tmp_gitlab_variable_secret_response.json.value }}
        dest: "{{ vault_mono_local_file_vault_init_secrets }}"
        mode: "0400"

# TODO: Wired logic, NO need to check file again, check from `Vault Monorepo | Configure Vault | Get Vault Initial Secret | GitLab | Write to file`
- name: Vault Monorepo | Configure Vault | Get Vault Initial Secret | Check for existing file post get
  ansible.builtin.stat:
    path: "{{ vault_mono_local_file_vault_init_secrets }}"
  register: vault_mono_local_file_stat_vault_init_secrets

- name: Vault Monorepo | Configure Vault | Get Vault Initial Secret | Set Fact
  when: vault_mono_local_file_stat_vault_init_secrets.stat.exists
  no_log: "{{ vault_mono_debug_no_log }}"
  ansible.builtin.set_fact:
    vault_mono_init_unseal_fact_init_secrets: "{{ lookup('ansible.builtin.file', vault_mono_local_file_vault_init_secrets) | from_json }}"
