---
# tasks file for hashicorp_vault
- name: "Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Create Vault Systemd Group: {{ vault_mono_install_systemd_group }}"
  ansible.builtin.group:
    name: "{{ vault_mono_install_systemd_group }}"
    state: present
    system: true

- name: "Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Create Vault Systemd User: {{ vault_mono_install_systemd_user }}"
  ansible.builtin.user:
    name: "{{ vault_mono_install_systemd_user }}"
    group: "{{ vault_mono_install_systemd_group }}"
    create_home: true
    home: "{{ vault_mono_install_path }}"
    shell: /bin/zsh
    system: true
  register: vault_mono_install_tmp_systemd_user_create_result

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Check zshrc file
  ansible.builtin.stat:
    path: "{{ vault_mono_install_tmp_systemd_user_create_result.home }}/.zshrc"
  register: vault_mono_install_tmp_systemd_user_zshrc_stat

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Create zshrc file
  when: not vault_mono_install_tmp_systemd_user_zshrc_stat.stat.exists
  ansible.builtin.file:
    group: "{{ vault_mono_install_systemd_group }}"
    path: "{{ vault_mono_install_tmp_systemd_user_create_result.home }}/.zshrc"
    owner: "{{ vault_mono_install_systemd_user }}"
    mode: "0644"
    state: touch

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Create UFW Vault application rules
  ansible.builtin.template:
    src: "{{ vault_mono_local_templates_dir }}/ufw-{{ vault_mono_install_ufw_rule_name }}.j2"
    dest: "{{ vault_mono_install_ufw_application_rule_file_path }}"
    mode: "0644"

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Enable Vault Application Port
  community.general.ufw:
    rule: allow
    name: "{{ vault_mono_install_ufw_rule_name }}"
    state: enabled

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Remove OS Package Vault
  ansible.builtin.apt:
    name: vault
    purge: true
    state: absent

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Create Directories
  ansible.builtin.file:
    name: "{{ item }}"
    mode: "0700"
    state: directory
    group: "{{ vault_mono_install_systemd_group }}"
    owner: "{{ vault_mono_install_systemd_user }}"
  with_items:
    - "{{ vault_mono_install_path }}"
    - "{{ vault_mono_tls_dir_path }}"
    - "{{ vault_mono_install_config_dir_path }}"
    - "{{ vault_mono_install_bin_dir_path }}"
    - "{{ vault_mono_install_tmp_dir_path }}"
  notify: Vault Monorepo | Setup Vault Server | Handlers | Restart Vault

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Add Vault server configuration file
  ansible.builtin.template:
    src: "{{ vault_mono_local_templates_dir }}/vault.hcl.j2"
    dest: "{{ vault_mono_install_config_file_path }}"
    mode: "0644"
    group: "{{ vault_mono_install_systemd_group }}"
    owner: "{{ vault_mono_install_systemd_user }}"
  notify: Vault Monorepo | Setup Vault Server | Handlers | Restart Vault

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Download Vault bin from {{ vault_mono_install_zip_url }}
  ansible.builtin.get_url:
    url: "{{ vault_mono_install_zip_url }}"
    dest: "{{ vault_mono_install_tmp_dir_path }}/{{ vault_mono_install_package }}"
    checksum:
      "sha256:{{ (lookup('url', vault_mono_install_checksum_file_url, wantlist=true) \
      | select('match', '.*' + vault_mono_install_package + '$') | first).split()[0] }}"
    timeout: "42"
    mode: "0600"
    group: "{{ vault_mono_install_systemd_group }}"
    owner: "{{ vault_mono_install_systemd_user }}"
  notify: Vault Monorepo | Setup Vault Server | Handlers | Restart Vault

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Unarchive Vault ZIP
  ansible.builtin.unarchive:
    src: "{{ vault_mono_install_tmp_dir_path }}/{{ vault_mono_install_package }}"
    dest: "{{ vault_mono_install_tmp_dir_path }}"
    # creates: "{{ role_path }}/files/vault"
    mode: "0400"
    group: "{{ vault_mono_install_systemd_group }}"
    owner: "{{ vault_mono_install_systemd_user }}"
    remote_src: true
  notify: Vault Monorepo | Setup Vault Server | Handlers | Restart Vault

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Install Vault
  ansible.builtin.copy:
    src: "{{ vault_mono_install_tmp_dir_path }}/vault"
    dest: "{{ vault_mono_install_bin_file_path }}"
    mode: "0500"
    group: "{{ vault_mono_install_systemd_group }}"
    owner: "{{ vault_mono_install_systemd_user }}"
    remote_src: true
  notify: Vault Monorepo | Setup Vault Server | Handlers | Restart Vault

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | cap_ipc_lock=ep
  community.general.capabilities:
    path: "{{ vault_mono_install_bin_file_path }}"
    capability: cap_ipc_lock=ep
    state: present

- name: Vault Monorepo | Setup Vault Server | Install Hashicorp Vault | Add Systemd Service File
  ansible.builtin.template:
    src: "{{ vault_mono_local_templates_dir }}/vault.service.j2"
    dest: "{{ vault_mono_install_systemd_service_file_loc }}"
    mode: "0644"
    group: root
    owner: root
  notify: Vault Monorepo | Setup Vault Server | Handlers | Restart Vault
