---
- name: Vault Monorepo | Configure Vault | Update Vault initial secret | GitLab
  block:
    - name: Vault Monorepo | Configure Vault | Update Vault initial secret | GitLab | Include variables
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/vars/gitlab_artifacts.yml"

    - name: Vault Monorepo | Configure Vault | Update Vault initial secret | GitLab | Create or update
      community.general.gitlab_project_variable:
        api_url: https://gitlab.com
        api_token: "{{ lookup('ansible.builtin.file', vault_mono_prerequisite_local_file_gitlab_gl_prod_api_key) | trim }}"
        project: "{{ vault_mono_gitlab_artifacts_user_project_path }}"
        purge: false
        variables:
          - name: "{{ vault_mono_gitlab_artifacts_vault_cicd_variable_key_init_file }}"
            value: "{{ lookup('ansible.builtin.file', vault_mono_local_file_vault_init_secrets) | trim }}"
            masked: false
            protected: false
            variable_type: file
