---
- name: Vault Monorepo | Common | Get Vault Config
  run_once: true
  ansible.builtin.set_fact:
    vault_mono_global_config: "{{ lookup('ansible.builtin.file', vault_mono_local_file_global_config) | from_json }}"

- name: Vault Monorepo | Bitwarden
  ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/011-bw.yml"

- name: Vault Monorepo | Common | OPENSSH PRIVATE KEY | Remove Password
  ansible.builtin.shell: |-
    cp {{ vault_mono_local_file_openssh_private_key }} {{ vault_mono_local_file_openssh_nopass_private_key }}
    chmod 600 {{ vault_mono_local_file_openssh_nopass_private_key }}
    ssh-keygen -p \
      -P {{ lookup('ansible.builtin.file', vault_mono_local_file_openssh_private_key_passphrase) }} \
      -N '' -f {{ vault_mono_local_file_openssh_nopass_private_key }}
  args:
    creates: "{{ vault_mono_local_file_openssh_nopass_private_key }}"

- name: Vault Monorepo | Bitwarden | ROOT CA | Remove Password
  ansible.builtin.shell: |-
    openssl rsa -in {{ vault_mono_local_file_root_ca_private_key }} \
        -passin pass:{{ lookup('ansible.builtin.file', vault_mono_local_file_root_ca_private_key_passphrase) }} \
        -passout pass:"" \
        -out {{ vault_mono_local_file_root_ca_private_key_no_pass }}
  args:
    creates: "{{ vault_mono_local_file_root_ca_private_key_no_pass }}"
