---
- name: Vault Monorepo | Common | Get Vault Config
  run_once: true
  ansible.builtin.set_fact:
    vault_mono_global_config: "{{ lookup('ansible.builtin.file', vault_mono_local_file_global_config) | from_json }}"

- name: Vault Monorepo | Bitwarden
  ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/011-bw.yml"
