---
- name: Vault Monorepo | Bitwarden | OPENSSH PRIVATE KEY
  no_log: "{{ vault_mono_debug_no_log }}"
  block:
    - name: Vault Monorepo | Bitwarden | OPENSSH PRIVATE KEY | Get Private Key Password
      ansible.builtin.shell: "bw get password 'OPENSSH PRIVATE KEY' --raw > {{ vault_mono_local_file_openssh_passphrase_private_key }}"
      args:
        creates: "{{ vault_mono_local_file_openssh_passphrase_private_key }}"

    - name: Vault Monorepo | Bitwarden | OPENSSH PRIVATE KEY | Download Private key
      ansible.builtin.shell: |-
        bw get attachment id_rsa \
        --itemid $(bw get item 'OPENSSH PRIVATE KEY' --raw | jq .id -r) \
        --output "{{ vault_mono_local_file_openssh_private_key }}"
        chmod 600 "{{ vault_mono_local_file_openssh_private_key }}"
      args:
        creates: "{{ vault_mono_local_file_openssh_private_key }}"

    - name: Vault Monorepo | Bitwarden | OPENSSH PRIVATE KEY | Download Public key
      ansible.builtin.shell: |-
        bw get attachment id_rsa.pub \
        --itemid $(bw get item 'OPENSSH PRIVATE KEY' --raw | jq .id -r) \
        --output {{ vault_mono_local_file_openssh_public_key }}
        chmod 600 {{ vault_mono_local_file_openssh_public_key }}
      args:
        creates: "{{ vault_mono_local_file_openssh_public_key }}"

- name: Vault Monorepo | Bitwarden | Linode | Get CLI PROD TOKEN
  no_log: "{{ vault_mono_debug_no_log }}"
  ansible.builtin.shell: >
    bw get item 'Linode' --raw |
    jq '.fields |
    .[] |
    select(.name == "LINODE_CLI_PROD_TOKEN") |
    .value' -r > {{ vault_mono_local_file_linode_cli_prod_token }}
  args:
    creates: "{{ vault_mono_local_file_linode_cli_prod_token }}"

- name: Vault Monorepo | Bitwarden | ROOT CA
  no_log: "{{ vault_mono_debug_no_log }}"
  block:
    - name: Vault Monorepo | Bitwarden | ROOT CA | Get Private Key Passphrase
      ansible.builtin.shell: |
        bw get password 'CA ROOT' --raw > "{{ vault_mono_local_file_root_ca_passphrase_private_key }}"
      args:
        creates: "{{ vault_mono_local_file_root_ca_passphrase_private_key }}"

    - name: Vault Monorepo | Bitwarden | ROOT CA | Download Private key
      ansible.builtin.shell: |-
        bw get attachment own_ca_root.key \
        --itemid $(bw get item 'CA ROOT' --raw | jq .id -r) \
        --output "{{ vault_mono_local_file_root_ca_private_key }}"
      args:
        creates: "{{ vault_mono_local_file_root_ca_private_key }}"

    - name: Vault Monorepo | Bitwarden | ROOT CA | Download Certificate
      ansible.builtin.shell: |-
        bw get attachment own_ca_root.cert \
        --itemid $(bw get item 'CA ROOT' --raw | jq .id -r) \
        --output "{{ vault_mono_local_file_root_ca_certificate }}"
      args:
        creates: "{{ vault_mono_local_file_root_ca_certificate }}"

- name: Vault Monorepo | Bitwarden | OpenPGP
  no_log: "{{ vault_mono_debug_no_log }}"
  block:
    - name: Vault Monorepo | Bitwarden | OpenPGP | Get Private Key Passphrase
      ansible.builtin.shell: |
        bw get password 'PGP PRIVATE KEY' --raw > "{{ vault_mono_local_file_openpgp_passphrase_private_key }}"
      args:
        creates: "{{ vault_mono_local_file_openpgp_passphrase_private_key }}"

    - name: Vault Monorepo | Bitwarden | OpenPGP | Download Private key
      ansible.builtin.shell: |-
        bw get attachment private.asc \
        --itemid $(bw get item 'PGP PRIVATE KEY' --raw | jq .id -r) \
        --output "{{ vault_mono_local_file_openpgp_private_key }}"
      args:
        creates: "{{ vault_mono_local_file_openpgp_private_key }}"

    - name: Vault Monorepo | Bitwarden | OpenPGP | Download Public key
      ansible.builtin.shell: |-
        bw get attachment public.asc \
        --itemid $(bw get item 'PGP PRIVATE KEY' --raw | jq .id -r) \
        --output "{{ vault_mono_local_file_openpgp_public_key }}"
      args:
        creates: "{{ vault_mono_local_file_openpgp_public_key }}"
