---
- name: Setup Vault | Server in linode | Create a new linode
  no_log: "{{ vault_mono_debug_no_log }}"
  linode_v4:
    label: "vault_server"
    access_token: "{{ lookup('ansible.builtin.file', vault_mono_local_file_linode_cli_prod_token) | trim }}"
    type: g6-standard-4
    region: ap-west
    image: linode/debian11
    authorized_keys: "{{ lookup('ansible.builtin.file', vault_mono_local_file_openssh_public_key) }}"
    state: present
  register: vault_mono_linode

- name: Setup Vault | Server in linode | Set new IP address
  ansible.builtin.set_fact:
    vault_mono_vault_server_public_ip: "{{ vault_mono_linode.instance.ipv4[0] }}"

- name: Setup Vault | Server in linode | Wait for the host to come online
  ansible.builtin.wait_for:
    port: 22
    host: "{{ vault_mono_vault_server_public_ip }}"
    timeout: 3
  register: vault_mono_server_ping_test
  retries: 100
  delay: 3
  until: 'vault_mono_server_ping_test.state is defined and vault_mono_server_ping_test.state == "started"'

- name: Vault Monorepo | Server in linode | Adding dynamic host
  ansible.builtin.add_host:
    hostname: "{{ vault_mono_server_ansible_inventory_name }}"
    ansible_host: "{{ vault_mono_vault_server_public_ip }}"
    ansible_connection: "ssh"
    ansible_port: 22
    ansible_user: root
    ansible_ssh_private_key_file: "{{ vault_mono_local_file_openssh_private_key }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: Vault Monorepo | Server in linode | Verify dynamic host
  delegate_to: "{{ vault_mono_server_ansible_inventory_name }}"
  ansible.builtin.ping:
  ignore_unreachable: true
  register: vault_mono_dynamic_host_ping

- name: Vault Monorepo | Server in linode | Adding dynamic host with new user {{ vault_mono_server_login_username }}
  ansible.builtin.add_host:
    hostname: "{{ vault_mono_server_ansible_inventory_name }}"
    ansible_host: "{{ vault_mono_vault_server_public_ip }}"
    ansible_connection: "ssh"
    ansible_port: 22
    ansible_user: "{{ vault_mono_server_login_username }}"
    ansible_ssh_private_key_file: "{{ vault_mono_local_file_openssh_private_key }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  when: vault_mono_dynamic_host_ping.msg is defined and '"Permission denied (publickey)" in vault_mono_dynamic_host_ping.msg'

- name: Vault Monorepo | Server in linode | Verify dynamic host with {{ vault_mono_server_login_username }}
  delegate_to: "{{ vault_mono_server_ansible_inventory_name }}"
  ansible.builtin.ping:
