---
- name: Vault Monorepo | Patch System | Install upgrade and install python3-pip
  ansible.builtin.raw: apt-get update && apt-get install -y python3-pip
  register: vault_mono_install_python_pip_result_raw
  changed_when: "'0 upgraded, 0 newly installed' not in vault_mono_install_python_pip_result_raw.stdout_lines | last"

- name: Vault Monorepo | Patch System | Set timezone as UTC
  community.general.timezone:
    name: UTC
    hwclock: UTC

- name: Vault Monorepo | Patch System | Install required packages
  ansible.builtin.apt:
    name:
      [
        libcap2-bin,
        zip,
        unzip,
        net-tools,
        build-essential,
        tar,
        wget,
        curl,
        ca-certificates,
        sudo,
        systemd,
        telnet,
        gnupg2,
        apt-transport-https,
        lsb-release,
        software-properties-common,
        locales,
        systemd-timesyncd,
        network-manager,
        gnupg2,
        gnupg,
        pigz,
        cron,
        acl,
        ufw,
        vim,
        python3-pip,
        git,
        fontconfig,
        gtk-update-icon-cache,
        libnss3,
        libatk1.0-0,
        libatk-bridge2.0-0,
        libgtk-3-0,
        bzip2,
        libgbm-dev,
        libglib2.0-dev,
        libdrm-dev,
        libasound2,
        jq,
        zsh,
      ]

- name: Linux Patching | Patch System | Install headers linux-headers-{{ ansible_kernel }}
  ansible.builtin.apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present
    update_cache: true

- name: Vault Monorepo | Patch System | Ensure a locale exists as en_US.UTF-8
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present
  environment:
    PATH: /usr/sbin:{{ ansible_env.PATH }}

- name: Vault Monorepo | Patch System | Create wheel and sudo groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items:
    - wheel
    - sudo

- name: Vault Monorepo | Patch System | Create Sudoers directory
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Vault Monorepo | Patch System | Allow group permissions
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ item.file_loc }}"
    content: "{{ item.rule }}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - file_loc: 1000-root
      rule: "root ALL=(ALL:ALL) ALL"
    - file_loc: 1100-sudo
      rule: "%sudo ALL=(ALL:ALL) ALL"
    - file_loc: 1200-wheel
      rule: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"

- name: Vault Monorepo | Patch System | Vault Group
  ansible.builtin.group:
    name: "{{ vault_mono_server_vault_systemd_group }}"
    state: present

- name: Vault Monorepo | Patch System | Add new user
  ansible.builtin.user:
    name: "{{ vault_mono_server_vault_systemd_user }}"
    group: "{{ vault_mono_server_vault_systemd_group }}"
    create_home: true
    home: "{{ vault_mono_install_path }}"
    groups: wheel
    append: true
    shell: /bin/zsh

- name: Vault Monorepo | Patch System | User zsh rc
  ansible.builtin.file:
    group: "{{ vault_mono_server_vault_systemd_group }}"
    path: "{{ vault_mono_install_path }}/zshrc"
    owner: "{{ vault_mono_server_vault_systemd_user }}"
    mode: "0644"
    state: touch

- name: Vault Monorepo | Patch System | Set authorized key
  ansible.posix.authorized_key:
    user: "{{ vault_mono_server_vault_systemd_user }}"
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ lookup('ansible.builtin.file', vault_mono_local_file_openssh_public_key) }}"
    - "{{ lookup('ansible.builtin.file', vault_mono_local_file_openssh_master_public_key) }}"

- name: Vault Monorepo | Patch System | SSHD Hardening Disable Password Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"

- name: Linux Patching | Patch System | Disable Wifi MAC randomization
  community.general.ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    mode: "0775"
  with_items:
    - section: "device"
      option: "wifi.scan-rand-mac-address"
      value: "no"
    - section: "device-mac-randomization"
      option: "wifi.scan-rand-mac-address"
      value: "no"
    - section: "ifupdown"
      option: "managed"
      value: "true"
    - section: "main"
      option: "plugins"
      value: "ifupdown,keyfile"
    - section: "connection"
      option: "wifi.powersave"
      value: 2

- name: Linux Patching | Patch System | Disable IPv6
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/70-disable-ipv6.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items:
    - name: net.ipv6.conf.all.disable_ipv6
      value: "1"
    - name: net.ipv6.conf.default.disable_ipv6
      value: "1"
    - name: net.ipv6.conf.lo.disable_ipv6
      value: "1"

- name: Linux Patching | Patch System | Set a hostname
  ansible.builtin.hostname:
    name: "{{ vault_mono_global_config.VAULT_ADDR_DOMAIN_NAME }}"
    use: debian

- name: Linux Patching | Patch System | Set Hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    owner: root
    group: root
    mode: "0644"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - regexp: '^127\.0\.0\.1'
      line: "127.0.0.1\tlocalhost"
    - regexp: '^127\.0\.1\.1'
      line: "127.0.1.1\t{{ vault_mono_global_config.VAULT_ADDR_DOMAIN_NAME }}"

- name: Linux Patching | Patch System | Enable network services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: [NetworkManager, systemd-timesyncd, systemd-resolved, ufw, cron]

- name: Linux Patching | Patch System | Apply Vault UFW Rule
  template:
    src: "{{ vault_mono_local_templates_dir }}/ufw-vault.j2"
    dest: /etc/ufw/applications.d/ufw-vault
    mode: "0644"

- name: Linux Patching | Patch System | Enable network services
  community.general.ufw:
    rule: allow
    name: "{{ item }}"
    state: enabled
  with_items:
    - OpenSSH
    - "{{ vault_mono_ufw_rule_name }}"
