---
- name: Vault Monorepo | Patch System | Install upgrade and install python3-pip
  ansible.builtin.raw: apt-get update && apt-get install -y python3-pip
  register: vault_mono_install_python_pip_result_raw
  changed_when: "'0 upgraded, 0 newly installed' not in vault_mono_install_python_pip_result_raw.stdout_lines | last"

- name: Vault Monorepo | Patch System | Set timezone as Asia/Kolkata
  community.general.timezone:
    name: Asia/Kolkata
    hwclock: local
  ignore_errors: true
  register: rv_linux_patching_hw_settime_result

- name: Vault Monorepo | Patch System | Set timezone via softlink
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/Asia/Kolkata"
    dest: /etc/localtime
    state: link
  when: rv_linux_patching_hw_settime_result.failed

- name: Vault Monorepo | Patch System | Ensure a locale exists as en_US.UTF-8
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present
  environment:
    PATH: /usr/sbin:{{ ansible_env.PATH }}

- name: Vault Monorepo | Patch System | Create wheel and sudo groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items:
    - wheel
    - sudo

- name: Vault Monorepo | Patch System | Create Sudoers directory
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Vault Monorepo | Patch System | Allow group permissions
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ item.file_loc }}"
    content: "{{ item.rule }}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - file_loc: 1000-root
      rule: "root ALL=(ALL:ALL) ALL"
    - file_loc: 1100-sudo
      rule: "%sudo ALL=(ALL:ALL) ALL"
    - file_loc: 1200-wheel
      rule: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"

- name: Vault Monorepo | Patch System | Add new user
  ansible.builtin.user:
    name: "{{ vault_mono_server_login_username }}"
    groups: wheel
    append: true
    shell: /bin/bash

- name: Vault Monorepo | Patch System | Set authorized key
  ansible.posix.authorized_key:
    user: "{{ vault_mono_server_login_username }}"
    state: present
    key: "{{ lookup('ansible.builtin.file', vault_mono_local_file_openssh_public_key) }}"

- name: Vault Monorepo | Patch System | SSHD Hardening Disable Password Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
