---
- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Get IP Address from DNS
  ansible.builtin.set_fact:
    vault_mono_server_vault_dig: "{{ lookup('community.general.dig', vault_mono_global_config.VAULT_ADDR_DOMAIN_NAME) }}"

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Get Public IP Address
  ansible.builtin.uri:
    url: https://ifconfig.me/all.json
  register: vault_mono_server_vault_ifconfig_me

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Configure
  ansible.builtin.copy:
    src: "{{ vault_mono_local_file_vault_server_config }}"
    dest: /etc/vault.d/vault.hcl
    mode: "0644"
    owner: "{{ vault_mono_server_vault_systemd_user }}"
    group: "{{ vault_mono_server_vault_systemd_user }}"
  notify: Vault Monorepo | Handlers | Restart Vault

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Write TLS Client CA Certificate To File for tls_client_ca_file
  ansible.builtin.copy:
    src: "{{ vault_mono_local_file_root_ca_certificate }}"
    dest: "/opt/vault/tls/root.crt"
    owner: "{{ vault_mono_server_vault_systemd_user }}"
    group: "{{ vault_mono_server_vault_systemd_user }}"
    mode: "0600"
    remote_src: false
  notify: Vault Monorepo | Handlers | Restart Vault

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Generate an OpenSSL private key
  community.crypto.openssl_privatekey:
    path: /opt/vault/tls/tls.key
    owner: "{{ vault_mono_server_vault_systemd_user }}"
    group: "{{ vault_mono_server_vault_systemd_user }}"
    mode: "0600"
  notify: Vault Monorepo | Handlers | Restart Vault

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Check existing certificate file
  ansible.builtin.stat:
    path: /opt/vault/tls/tls_chain.crt
  register: vault_mono_server_vault_certificate_file_stat

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Get information on generated certificate
  when: vault_mono_server_vault_certificate_file_stat.stat.exists
  community.crypto.x509_certificate_info:
    path: /opt/vault/tls/tls_chain.crt
    valid_at:
      point_1: "+1d"
  register: vault_mono_server_vault_x509_certificate_info
  ignore_errors: true

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Generate an OpenSSL Certificate Signing Request
  when: >
    (
      not vault_mono_server_vault_certificate_file_stat.stat.exists
    )
    or
    (
      vault_mono_server_vault_x509_certificate_info.valid_at is defined
      and
      (
        (
          not vault_mono_server_vault_x509_certificate_info.valid_at.point_1
        )
        or
        (
          vault_mono_server_vault_x509_certificate_info.subject.commonName != vault_mono_global_config.VAULT_ADDR_DOMAIN_NAME
        )
      )
    )
    or
    (
      vault_mono_server_vault_x509_certificate_info.failed is defined and vault_mono_server_vault_x509_certificate_info.failed
    )
  community.crypto.openssl_csr_pipe:
    privatekey_path: /opt/vault/tls/tls.key
    common_name: "{{ vault_mono_global_config.VAULT_ADDR_DOMAIN_NAME }}"
    subject_alt_name:
      - "DNS:{{ vault_mono_global_config.VAULT_ADDR_DOMAIN_NAME }}"
      - "IP:{{ vault_mono_server_vault_dig }}"
      - "IP:{{ vault_mono_server_vault_ifconfig_me.json.ip_addr }}"
    subject_alt_name_critical: true
    basic_constraints: CA:FALSE
    basic_constraints_critical: true
    key_usage:
      - digitalSignature
      - nonRepudiation
      - keyEncipherment
      - dataEncipherment
      - keyCertSign
      - cRLSign
    key_usage_critical: true
    extended_key_usage:
      - serverAuth
    extended_key_usage_critical: true
  register: vault_mono_server_vault_openssl_csr_pipe
  notify: Vault Monorepo | Handlers | Restart Vault

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Generate an OpenSSL certificate signed with your own CA certificate
  delegate_to: localhost
  when: vault_mono_server_vault_openssl_csr_pipe.csr is defined
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ vault_mono_server_vault_openssl_csr_pipe.csr }}"
    ownca_path: "{{ vault_mono_local_file_root_ca_certificate }}"
    ownca_privatekey_path: "{{ vault_mono_local_file_root_ca_private_key }}"
    provider: ownca
    ownca_not_after: "+30d"
  register: vault_mono_server_vault_x509_certificate_pipe
  notify: Vault Monorepo | Handlers | Restart Vault

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Write Certificate To File
  when: vault_mono_server_vault_x509_certificate_pipe.certificate is defined
  ansible.builtin.copy:
    content: "{{ vault_mono_server_vault_x509_certificate_pipe.certificate }}"
    dest: "/opt/vault/tls/tls.crt"
    owner: "{{ vault_mono_server_vault_systemd_user }}"
    group: "{{ vault_mono_server_vault_systemd_user }}"
    mode: "0600"
  notify: Vault Monorepo | Handlers | Restart Vault

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Set certificate chain
  delegate_to: localhost
  when: vault_mono_server_vault_x509_certificate_pipe.certificate is defined
  ansible.builtin.set_fact:
    vault_mono_server_vault_chain_x509_certificate: |+
      {{ vault_mono_server_vault_x509_certificate_pipe.certificate | trim }}
      {{ lookup('ansible.builtin.file', vault_mono_local_file_root_ca_certificate) }}

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Write Certificate Chain To File
  when: vault_mono_server_vault_x509_certificate_pipe.certificate is defined
  ansible.builtin.copy:
    content: "{{ vault_mono_server_vault_chain_x509_certificate }}"
    dest: "/opt/vault/tls/tls_chain.crt"
    owner: "{{ vault_mono_server_vault_systemd_user }}"
    group: "{{ vault_mono_server_vault_systemd_user }}"
    mode: "0600"
  notify: Vault Monorepo | Handlers | Restart Vault

- name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate | Write Cert To File
  ansible.builtin.meta: flush_handlers
