---
- name: Vault Post Install Steps | Initialize | Get Vault Health Status
  environment: # https://stackoverflow.com/questions/47890394/ansible-uri-module-with-cacert-option
    SSL_CERT_FILE: "{{ vault_mono_local_file_root_certificate }}"
  ansible.builtin.uri:
    url: "https://{{ vault_mono_global_config.VAULT_ADDR_DOMAIN_NAME }}:{{ vault_mono_global_config.VAULT_ADDR_PORT }}/v1/sys/health"
    method: GET
    # ca_path: "{{ vault_mono_local_file_root_certificate }}"
    client_cert: "{{ vault_mono_local_file_client_certificate }}"
    client_key: "{{ vault_mono_local_file_client_private_key }}"
    status_code: [429, 472, 473, 501, 503, 200]
    validate_certs: true
  register: vault_mono_health

- name: Vault Post Install Steps | Initialize | Initialize
  when: not vault_mono_health.json.initialized
  no_log: "{{ vault_mono_debug_no_log }}"
  environment: # https://stackoverflow.com/questions/47890394/ansible-uri-module-with-cacert-option
    SSL_CERT_FILE: "{{ vault_mono_local_file_root_certificate }}"
  ansible.builtin.uri:
    url: "https://{{ vault_mono_global_config.VAULT_ADDR_DOMAIN_NAME }}:{{ vault_mono_global_config.VAULT_ADDR_PORT }}/v1/sys/init"
    method: POST
    # ca_path: "{{ vault_mono_local_file_root_certificate }}"
    client_cert: "{{ vault_mono_local_file_client_certificate }}"
    client_key: "{{ vault_mono_local_file_client_private_key }}"
    validate_certs: true
    body_format: json
    status_code: 200
    body:
      secret_shares: 5
      secret_threshold: 3
  register: vault_mono_sys_init

- name: Vault Monorepo | Initialize | Write init secrets To File
  when: vault_mono_sys_init.json is defined and vault_mono_sys_init.json.root_token is defined
  no_log: "{{ vault_mono_debug_no_log }}"
  ansible.builtin.copy:
    content: |
      {{ vault_mono_sys_init.json | to_nice_json(indent=2) }}
    dest: "{{ vault_mono_local_file_vault_init_secrets }}"
    mode: "0400"

- name: Vault Monorepo | Initialize | Read init secrets from File
  no_log: "{{ vault_mono_debug_no_log }}"
  run_once: true
  ansible.builtin.set_fact:
    vault_mono_init_secrets: "{{ lookup('ansible.builtin.file', vault_mono_local_file_vault_init_secrets) | from_json }}"

- name: Vault Post Install Steps | Initialize | Unseal
  when: >
    (
      vault_mono_sys_init.json is defined and vault_mono_sys_init.json.root_token is defined
    )
    or
    (
      vault_mono_health.json.initialized and vault_mono_health.json.sealed
    )
  environment: # https://stackoverflow.com/questions/47890394/ansible-uri-module-with-cacert-option
    SSL_CERT_FILE: "{{ vault_mono_local_file_root_certificate }}"
  no_log: "{{ vault_mono_debug_no_log }}"
  ansible.builtin.uri:
    url: "https://{{ vault_mono_global_config.VAULT_ADDR_DOMAIN_NAME }}:{{ vault_mono_global_config.VAULT_ADDR_PORT }}/v1/sys/unseal"
    method: POST
    # ca_path: "{{ vault_mono_local_file_root_certificate }}"
    client_cert: "{{ vault_mono_local_file_client_certificate }}"
    client_key: "{{ vault_mono_local_file_client_private_key }}"
    validate_certs: true
    body_format: json
    status_code: 200
    body:
      key: "{{ item }}"
  register: vault_mono_sys_unseal
  with_items:
    - "{{ vault_mono_init_secrets['keys'][0] }}"
    - "{{ vault_mono_init_secrets['keys'][1] }}"
    - "{{ vault_mono_init_secrets['keys'][2] }}"
