---
- name: Vault Monorepo | Terraform Tntermittent CA Certificate | Generate an OpenSSL private key
  community.crypto.openssl_privatekey:
    path: "{{ vault_mono_local_file_terraform_intermittent_ca_private_key }}"
    size: 8192
    mode: "0400"
  register: arpanrec_cert_tmp_private_key_details

- name: Vault Monorepo | Terraform Tntermittent CA Certificate | Check for existing Certificate
  ansible.builtin.stat:
    path: "{{ vault_mono_local_file_terraform_intermittent_ca_certificate }}"
  register: arpanrec_cert_tmp_file_stat_cert

- name: Vault Monorepo | Terraform Tntermittent CA Certificate | Get information on existing certificate
  when: arpanrec_cert_tmp_file_stat_cert.stat.exists
  community.crypto.x509_certificate_info:
    path: "{{ vault_mono_local_file_terraform_intermittent_ca_certificate }}"
    valid_at:
      point_1: "+1d"
  register: arpanrec_cert_tmp_x509_certificate_info
  ignore_errors: true

- name: Vault Monorepo | Terraform Tntermittent CA Certificate | Generate an OpenSSL Certificate Signing Request
  when: >
    (
      not arpanrec_cert_tmp_file_stat_cert.stat.exists
    )
    or
    (
      arpanrec_cert_tmp_x509_certificate_info.valid_at is defined
      and
      (
        not arpanrec_cert_tmp_x509_certificate_info.valid_at.point_1
      )
    )
    or
    (
      arpanrec_cert_tmp_x509_certificate_info.failed is defined
      and
      arpanrec_cert_tmp_x509_certificate_info.failed
    )
    or
    (
      arpanrec_cert_tmp_file_stat_cert.stat.exists
      and
      (
        arpanrec_cert_tmp_private_key_details['diff']['after']['public_key_fingerprints']['sha256']
        !=
        arpanrec_cert_tmp_x509_certificate_info['public_key_fingerprints']['sha256']
      )
    )
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ vault_mono_local_file_terraform_intermittent_ca_private_key }}"
    common_name: Vault M Domain Cert
    basic_constraints: CA:TRUE
    basic_constraints_critical: true
    key_usage:
      - digitalSignature
      - nonRepudiation
      - keyEncipherment
      - dataEncipherment
      - keyCertSign
      - cRLSign
    key_usage_critical: true
    extended_key_usage:
      - serverAuth
      - clientAuth
      - codeSigning
      - emailProtection
      - timeStamping
      - OCSPSigning
      - msCTLSign
      - msEFS
    extended_key_usage_critical: true
    create_subject_key_identifier: true
  register: arpanrec_cert_tmp_csr_result

- name: Vault Monorepo | Terraform Tntermittent CA Certificate | Generate an OpenSSL certificate signed with your own CA certificate
  when: arpanrec_cert_tmp_csr_result.csr is defined
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ arpanrec_cert_tmp_csr_result.csr }}"
    ownca_privatekey_path: "{{ vault_mono_local_file_root_ca_private_key }}"
    ownca_privatekey_passphrase: "{{ lookup('ansible.builtin.file', vault_mono_local_file_root_ca_private_key_passphrase) }}"
    ownca_path: "{{ vault_mono_local_file_root_ca_certificate }}"
    provider: ownca
    selfsigned_not_after: "+{{ vault_mono_local_file_terraform_intermittent_ca_validity }}d"
  register: vault_mono_local_file_terraform_intermittent_ca_x509_certificate_pipe

- name: Vault Monorepo | Terraform Tntermittent CA Certificate | Create Chain
  when: vault_mono_local_file_terraform_intermittent_ca_x509_certificate_pipe.certificate is defined
  ansible.builtin.copy:
    content: |+
      {{ vault_mono_local_file_terraform_intermittent_ca_x509_certificate_pipe.certificate | trim }}
      {{ lookup('ansible.builtin.file', vault_mono_local_file_root_ca_certificate) }}
    dest: "{{ vault_mono_local_file_terraform_intermittent_ca_certificate }}"
    mode: "0400"
