---
- name: Vault Monorepo | Terraform Codified Vault | Terraform Apply
  community.general.terraform:
    project_path: "{{ playbook_dir }}/../terraform"
    state: present
    force_init: true
    backend_config:
      path: "{{ vault_mono_local_file_codified_vault_terraform_local_backend_path }}"
  environment:
    TF_VAR_vault_mono_vault_root_token: "{{ vault_mono_init_secrets.root_token }}"
    TF_VAR_vault_mono_local_file_global_config: "{{ vault_mono_local_file_global_config }}"
    TF_VAR_vault_mono_local_file_root_ca_certificate: "{{ vault_mono_local_file_root_ca_certificate }}"
    TF_VAR_vault_mono_local_file_client_private_key: "{{ vault_mono_local_file_client_private_key }}"
    TF_VAR_vault_mono_local_file_client_certificate: "{{ vault_mono_local_file_client_certificate }}"
  register: vault_mono_codified_vault_output
  ignore_errors: true

- name: Vault Monorepo | Terraform Codified Vault Error | Terraform Error
  when: vault_mono_codified_vault_output.failed
  ansible.builtin.debug:
    msg: "{{ item | regex_replace('\\u001b.*0m', '') | trim }}"
  register: vault_mono_codified_vault_output_debug
  with_items:
    - "{{ vault_mono_codified_vault_output.stdout_lines }}"
    - "{{ vault_mono_codified_vault_output.stderr_lines }}"

- name: Vault Monorepo | Terraform Codified Vault Error | Terraform Fail
  when: vault_mono_codified_vault_output.failed
  ansible.builtin.fail:
    msg: "Terraform Apply Failed, Check above errors"
