---
- name: Vault Monorepo | Gitlab Vault Init Secret Get | Include variables
  no_log: "{{ vault_mono_debug_no_log }}"
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/vars/gitlab_artifacts.yml"

- name: Vault Monorepo | Gitlab Vault Init Secret Get | Check for existing
  no_log: "{{ vault_mono_debug_no_log }}"
  ansible.builtin.uri:
    url: "https://gitlab.com/api/v4/projects/\
      {{ vault_mono_gitlab_artifacts_project_id }}/variables/\
      {{ vault_mono_gitlab_artifacts_vault_cicd_variable_key_init_file }}"
    method: GET
    headers:
      "PRIVATE-TOKEN": "{{ lookup('ansible.builtin.file', vault_mono_local_file_gitlab_gl_prod_api_key) | trim }}"
    status_code:
      - 200
      - 404
  register: vault_mono_tmp_gitlab_variable_secret_response

- name: Vault Monorepo | Gitlab Vault Init Secret Get | Write to file
  when: vault_mono_tmp_gitlab_variable_secret_response.status == 200
  no_log: "{{ vault_mono_debug_no_log }}"
  ansible.builtin.copy:
    content: |
      {{ vault_mono_tmp_gitlab_variable_secret_response.json.value }}
    dest: "{{ vault_mono_local_file_vault_init_secrets }}"
    mode: "0400"
