---
- name: Get Server Info
  hosts: localhost
  gather_facts: true
  vars:
    vault_mono_server_ansible_inventory_name: vault_mono_server_ansible_inventory
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
    - name: Vault Monorepo | Common Tasks
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/010-common.yml"

    - name: Vault Monorepo | Wirte Private key to file
      ansible.builtin.copy:
        content: "{{ vault_mono_bw_secrets.OPENSSH_PRIVATE_KEY }}"
        dest: "{{ vault_mono_private_key_file }}"
        mode: "600"

    - name: Vault Monorepo | Create serevr
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/100-server_in_linode.yml"

- name: Get Server Info
  hosts: vault_mono_server_ansible_inventory
  gather_facts: true
  become: true
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
    - name: Vault Monorepo | Common Tasks
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/010-common.yml"
      delegate_to: localhost

    - name: Vault Monorepo | Patch System
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/200-patch_system.yml"
      when: false

    - name: Vault Monorepo | Install Hashicorp Vault
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/300-install_vault.yml"
      when: false

    - name: Vault Monorepo | Setup Hashicorp Vault
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/400-post_install.yml"
