---
- name: Get Server Information
  hosts: localhost
  gather_facts: true
  vars:
    vault_mono_server_ansible_inventory_name: vault_mono_server_ansible_inventory
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
    - name: Vault Monorepo | Check for tools
      run_once: true
      ansible.builtin.shell: "command -v {{ item }} >/dev/null 2>&1"
      changed_when: false
      with_items:
        - terraform
        - bw
        - jq
        - gpg
      tags:
        - always

    - name: Vault Monorepo | Mandatory directories
      run_once: true
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        mode: "0750"
      with_items:
        - "{{ vault_mono_local_files_dir }}"
        - "{{ vault_mono_prerequisite_files_dir }}"
        - "{{ vault_mono_mutual_tls_files_dir }}"

    - name: Vault Monorepo | Common Tasks
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/010-common.yml"
      tags:
        - patch_server
        - install_vault
        - vault_tls

    - name: Vault Monorepo | Create serevr
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/100-server_in_linode.yml"
      tags:
        - patch_server
        - install_vault
        - vault_tls

- name: Setup Vault Server
  hosts: vault_mono_server_ansible_inventory
  gather_facts: true
  become: true
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
    - name: Vault Monorepo | Common Tasks
      delegate_to: localhost
      become: false
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/010-common.yml"
      tags:
        - patch_server
        - install_vault
        - vault_tls

    - name: Vault Monorepo | Get vault systemd group
      ansible.builtin.set_fact:
        vault_mono_server_vault_systemd_group: vault
        vault_mono_server_vault_systemd_user: vault
          tags:
            - patch_server
            - install_vault
            - vault_tls


    - name: Vault Monorepo | Patch System
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/200-patch_system.yml"
      tags:
        - patch_server

    - name: Vault Monorepo | Install Hashicorp Vault
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/300-install_vault.yml"
      tags:
        - install_vault

    - name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/400-vault_tls.yml"
      tags:
        - vault_tls

  handlers:
    - name: Vault Monorepo | Handlers | Restart Vault
      ansible.builtin.service:
        name: vault
        state: "{{ item }}"
      with_items:
        - reloaded
        - restarted

- name: Client setup
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
    - name: Vault Monorepo | Common Tasks
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/010-common.yml"
      tags:
        - vault_init_unseal
        - codified_vault

    - name: Vault Monorepo | Client Certificate
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/500-client_cert.yml"
      tags:
        - vault_init_unseal
        - codified_vault

    - name: Vault Monorepo | Vault Init Secret Get
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/550-get_vault_init_secret.yml"
      tags:
        - vault_init_unseal
        - codified_vault

    - name: Vault Monorepo | Initialize
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/600-vault_init_unseal.yml"
      tags:
        - vault_init_unseal

    - name: Vault Monorepo | Vault Init Secret Update
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/650-update_vault_init_secret.yml"
      tags:
        - vault_init_unseal

    - name: Vault Monorepo | Terraform Codified Vault
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/700-codified_vault_gitlab.yml"
      tags:
        - codified_vault
