---
- name: Get Server Information
  hosts: localhost
  gather_facts: true
  vars:
    vault_mono_server_ansible_inventory_name: vault_mono_server_ansible_inventory
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
    - name: Vault Monorepo | Common Tasks
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/010-common.yml"
      tags:
        - patch_server
        - install_vault
        - vault_tls

    - name: Vault Monorepo | Wirte Private key to file
      ansible.builtin.copy:
        content: "{{ vault_mono_bw_secrets.OPENSSH_PRIVATE_KEY }}"
        dest: "{{ vault_mono_local_file_openssh_private_key }}"
        mode: "600"
      tags:
        - patch_server
        - install_vault
        - vault_tls

    - name: Vault Monorepo | Create serevr
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/100-server_in_linode.yml"
      tags:
        - patch_server
        - install_vault
        - vault_tls

- name: Setup Vault Server
  hosts: vault_mono_server_ansible_inventory
  gather_facts: true
  become: true
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
    - name: Vault Monorepo | Common Tasks
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/010-common.yml"
      tags:
        - patch_server
        - install_vault
        - vault_tls

    - name: Vault Monorepo | Patch System
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/200-patch_system.yml"
      tags:
        - patch_server

    - name: Vault Monorepo | Install Hashicorp Vault
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/300-install_vault.yml"
      tags:
        - install_vault

    - name: Vault Monorepo | Setup Hashicorp Vault TLS Certificate
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/400-vault_tls.yml"
      tags:
        - vault_tls

  handlers:
    - name: Vault Monorepo | Handlers | Restart Vault
      ansible.builtin.service:
        name: vault
        state: restarted

- name: Client setup
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
    - name: Vault Monorepo | Common Tasks
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/010-common.yml"
      tags:
        - vault_init
        - codified_vault

    - name: Vault Monorepo | Client Certificate
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/500-client_cert.yml"
      tags:
        - vault_init
        - codified_vault

    - name: Vault Monorepo | Initialize
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/600-init.yml"
      tags:
        - vault_init

    - name: Vault Monorepo | terraform_codified_vault
      community.general.terraform:
        project_path: "{{ playbook_dir }}/../terraform"
        state: present
      tags:
        - codified_vault
