name: Master Application Flow

"on":
  push:
    branches:
      #- "feature/**"
      - none
permissions:
  contents: read

jobs:
  master_flow:
    runs-on: ubuntu-latest
    container:
      image: arpanrecme/vaultmonorepo:9
    steps:
      - uses: actions/checkout@v3
      - name: Execute Script
        run: |
          ansible-galaxy install -r requirements.yml
          bw login --apikey --quiet
          export BW_SESSION=$(bw unlock "${BW_MASTERPASSWORD}" --raw)
          ansible-playbook site.yml
          bw logout
          bw status
        env:
          BW_CLIENTID: ${{ secrets.BW_CLIENTID }}
          BW_CLIENTSECRET: ${{ secrets.BW_CLIENTSECRET }}
          BW_MASTERPASSWORD: ${{ secrets.BW_MASTERPASSWORD }}
